#!/bin/bash

echo "$(grep "MiB Mem" ./part2 | awk '{print $4,$6,$8,$10}')" > test777
echo "$(grep "MiB Swap" ./part2 | awk '{print $3,$5,$7,$9}')" > test888
echo "$(grep -v "MiB" ./part2)" > test999
a="$(cat test777)"
echo "${a//./,}" > "test777"
a="$(cat test888)"
echo "${a//./,}" > "test888"
a="$(cat test999)"
echo "${a//./,}" > "test999"
echo "$(grep "4750" ./part2)" > test666
a="$(cat test666)"
echo "${a//./,}" > "test666"
echo "$(grep "4751" ./part2)" > test555
a="$(cat test555)"
echo "${a//./,}" > "test555"