#!/bin/bash

echo "$(grep "MiB Mem" ./test222 | awk '{print $4,$6,$8,$10}')" > test777
echo "$(grep "MiB Swap" ./test222 | awk '{print $3,$5,$7,$9}')" > test888
echo "$(grep -v "MiB" ./test222)" > test999